Action
- Maya installer

diff --git a/.github/workflows/win-generate-sign-installer.yaml b/.github/workflows/win-generate-sign-installer.yaml
--- a/.github/workflows/win-generate-sign-installer.yaml
+++ b/.github/workflows/win-generate-sign-installer.yaml
@@ -69,7 +69,6 @@ jobs:
         with:
           ref: main
 
-      # Continue with the build
       - name: Fetch VERSION
         uses: dsaltares/fetch-gh-release-asset@master
         with:
@@ -172,4 +171,95 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: main
+
+      - name: Fetch VERSION
+        uses: dsaltares/fetch-gh-release-asset@master
+        with:
+          repo: '${{ github.repository }}'
+          version: "tags/${{ env.WINDOWS_MAYA_TAG }}"
+          file: "VERSION"
+          target: "${{ env.WINDOWS_MAYA_INNO_DIR }}/VERSION"
+
+      - name: Modify verion in .iss
+        shell: bash
+        run: |
+          VERSION=$(cat ${{ env.WINDOWS_MAYA_INNO_DIR }}/VERSION)
+          sed -i "s/^#define MyAppVersion .*/#define MyAppVersion \"${VERSION}\"/" "${{ env.WINDOWS_MAYA_INNO }}"
+
+      # Generate installer
+      - name: Fetch Release
+        uses: dsaltares/fetch-gh-release-asset@master
+        with:
+          repo: '${{ github.repository }}'
+          version: "tags/${{ env.WINDOWS_MAYA_TAG }}"
+          file: "${{ env.WINDOWS_MAYA_ZIP }}"
+        
+      - name: Unzip Releases
+        run: |
+          Expand-Archive -Path ${{ env.WINDOWS_MAYA_ZIP }} -DestinationPath ${{ env.WINDOWS_MAYA_INNO_DIR }}
+
+      - name: Create Installer - Inno Setup Action
+        uses: Minionguyjpro/Inno-Setup-Action@v1.1.0
+        with:
+          path: "${{ env.WINDOWS_MAYA_INNO }}"
+
+      - name: Check if Windows Build Was Successful
+        shell: bash
+        run: |
+          if [ ! -e "output/${{ env.WINDOWS_MAYA_INSTALLER }}" ]; then
+            echo "Windows build failed"
+            exit 1
+          fi
+
+      # Sign installer
+      - name: Setup Certificate 
+        run: |
+            echo "${{ secrets.WINDOWS_SM_CLIENT_CERT_FILE_B64 }}" > /d/Certificate_pkcs12.b64
+            certutil -decode /d/Certificate_pkcs12.b64 /d/Certificate_pkcs12.p12
+            cat /d/Certificate_pkcs12.p12 
+            certutil -p "${{ secrets.WINDOWS_SM_CLIENT_CERT_PASSWORD }}" /d/Certificate_pkcs12.p12
+        shell: bash 
+            # The last line to test if the cert & password are valid
   
+      - name: Set variables 
+        id: variables 
+        run: |
+            echo "SM_HOST=${{ secrets.WINDOWS_SM_HOST }}" >> "$GITHUB_ENV" 
+            echo "SM_API_KEY=${{ secrets.WINDOWS_SM_API_KEY }}" >> "$GITHUB_ENV" 
+            echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV" 
+            echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.WINDOWS_SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
+            echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH 
+            echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH 
+            echo "C:\Program Files\DigiCert\DigiCert One Signing Manager Tools" >> $GITHUB_PATH 
+        shell: bash 
+  
+      - name: Setup SSM KSP on windows latest 
+        run: |
+            curl -X GET  https://one.digicert.com/signingmanager/api-ui/v1/releases/smtools-windows-x64.msi/download -H "x-api-key:%SM_API_KEY%" -o smtools-windows-x64.msi 
+            msiexec /i smtools-windows-x64.msi /quiet /qn 
+            smksp_registrar.exe list 
+            smctl.exe keypair ls 
+            C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user 
+            smksp_cert_sync.exe 
+        shell: cmd 
+  
+      - name: Signing using Signtool 
+        run: signtool.exe sign /debug /sha1 ${{ secrets.WINDOWS_SM_CODE_SIGNING_CERT_SHA1_HASH }} /v /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 "output\${{ env.WINDOWS_MAYA_INSTALLER }}" 
+
+      - name: Verify the Signature
+        run: signtool.exe verify /pa /v "output\${{ env.WINDOWS_MAYA_INSTALLER }}"
+
+      # Generating release
+      - name: Check dir
+        run: |
+          tree /F
+
+      - name: Upload installer to existing release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: output/${{ env.WINDOWS_MAYA_INSTALLER }}
+          asset_name: ${{ env.WINDOWS_MAYA_INSTALLER }}
+          tag: ${{ env.WINDOWS_MAYA_TAG }}
+          overwrite: true
+          make_latest: true
